export const PLATFORMS = [
  { value: 'nes', label: 'Nintendo (NES)' },
  { value: 'snes', label: 'Super Nintendo (SNES)' },
  { value: 'n64', label: 'Nintendo 64' },
  { value: 'gamecube', label: 'Nintendo GameCube' },
  { value: 'wii', label: 'Nintendo Wii' },
  { value: 'wiiu', label: 'Nintendo Wii U' },
  { value: 'switch', label: 'Nintendo Switch' },
  { value: 'gameboy', label: 'Game Boy' },
  { value: 'gbc', label: 'Game Boy Color' },
  { value: 'gba', label: 'Game Boy Advance' },
  { value: 'ds', label: 'Nintendo DS' },
  { value: '3ds', label: 'Nintendo 3DS' },
  { value: 'ps1', label: 'PlayStation' },
  { value: 'ps2', label: 'PlayStation 2' },
  { value: 'ps3', label: 'PlayStation 3' },
  { value: 'ps4', label: 'PlayStation 4' },
  { value: 'ps5', label: 'PlayStation 5' },
  { value: 'psp', label: 'PlayStation Portable' },
  { value: 'vita', label: 'PlayStation Vita' },
  { value: 'xbox', label: 'Xbox' },
  { value: 'xbox360', label: 'Xbox 360' },
  { value: 'xboxone', label: 'Xbox One' },
  { value: 'xboxseries', label: 'Xbox Series X/S' },
  { value: 'genesis', label: 'Sega Genesis/Mega Drive' },
  { value: 'saturn', label: 'Sega Saturn' },
  { value: 'dreamcast', label: 'Sega Dreamcast' },
  { value: 'gamegear', label: 'Sega Game Gear' },
  { value: 'atari2600', label: 'Atari 2600' },
  { value: 'pc', label: 'PC/Computer' },
  { value: 'other', label: 'Other' }
];